### ISSUE TITLE
Cannot fully import settings from 1.0.13.0

### ISSUE THREAD

**Issue by LouisJeanneau** [qwertydog/Reddit-Wallpaper-Changer#11]
When trying to import settings from an .xml file that was exported on 1.0.13.0 (or any version not containing the includeNSFW option), the import will fail halfway through.

Error message (in french) : 
![image](https://user-images.githubusercontent.com/18231902/210666070-bf4c0b27-04eb-4141-9d44-0d1667a48cab.png)

I'm sure it's because the `IncludeNsfw` tag is missing from the xml file.

https://github.com/qwertydog/Reddit-Wallpaper-Changer/blob/2e887735b303f7e6a8bfc97e77758e6b6a77aaa2/Reddit%20Wallpaper%20Changer/HelperMethods.cs#L100

Haven't done C# in a year but it might be coming from trying to access `InnerText` property of an absent `xn["IncludeNsfw"]`

**Comment by qwertydog** [comment]
Hi, thanks for the bug report. This should be fixed in the latest version (v1.0.21.0)
