### ISSUE TITLE
Feature Request: Option to set wallpaper on all virtual desktops

### ISSUE THREAD

**Issue by jpcaldwell30** [qwertydog/Reddit-Wallpaper-Changer#16]
I wanted to ask if it would be possible to add a "set on all desktops" option to RWC. I love the app, but one thing that drives me nuts is that it will only set the wallpaper on the current desktop and not all of them. I regularly use Windows 11's virtual desktop feature and would love to have RWC change the desktop backgrounds to the same background at once across all desktops.

**Comment by qwertydog** [comment]
Hi, I've added a setting for this in the latest version
