### ISSUE TITLE
Doesn't find NSFW posts

### ISSUE THREAD

**Issue by Sir-Prise** [qwertydog/Reddit-Wallpaper-Changer#4]
I noticed that the program doesn't find any NSFW posts. The API only returns NSFW posts when you're logged in or have `&include_over_18=on` in the URL, so this snipped should be added to the query.

**Comment by qwertydog** [comment]
Thanks, this should be fixed in the latest version

**Comment by Sir-Prise** [comment]
Thank you very much. Where do I find the latest version? On the release
page it's still the version from May 2019 :(

**Comment by qwertydog** [comment]
Yea the release page is a bit misleading, please ignore the date it is actually the latest version
