### ISSUE TITLE
History/Favourites/Blacklist empty

### ISSUE THREAD

**Issue by kroese** [qwertydog/Reddit-Wallpaper-Changer#5]
The program works okay, but the History/Favourites/Blacklist lists stay empty. Tried running it as Administrator as suggested in a previous issue, but it made no difference.

**Comment by Vorenu5** [comment]
I'm having the same issue (ran as administrator or not)

**Comment by qwertydog** [comment]
@kroese @Vorenu5 Can you please upload a copy of the logs? Restart the program, then upload via About -> Log File -> Upload Log, then paste the link. Or upload the file manually, it should be located in C:\Users\<Your User Name>\AppData\Roaming\Reddit Wallpaper Changer\Logs\RWC.log

**Comment by Vorenu5** [comment]
[RWC.log](https://github.com/qwertydog/Reddit-Wallpaper-Changer/files/8749568/RWC.log)

**Comment by Vorenu5** [comment]
Update: Uninstalling, then deleting everything in "C:\Users<Your User Name>\AppData\Roaming\Reddit Wallpaper Changer", then reinstalling and running first time as administrator fixed this issue for me. SQL database has valid tables and are updating now.

**Comment by qwertydog** [comment]
Fixed in #6
