### ISSUE TITLE
RWC Disabled after 50 failed attempts

### ISSUE THREAD

**Issue by zxcV32** [qwertydog/Reddit-Wallpaper-Changer#7]
RWC Disabled after failed attempts.

![image](https://user-images.githubusercontent.com/18421306/180588771-907360d9-6cdb-44fb-950c-3532e6ba18ef.png)

Logs:
https://pastebin.com/FwWCGJuE

**Comment by zxcV32** [comment]
I noticed that it is an API behavior. I had to set the time to week instead of day or hour for it to work.

**Comment by qwertydog** [comment]
Which subreddits are you using? If there are no matching posts during that time (past hour/past day), then no results will be returned from the API
