### ISSUE TITLE
Remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by rh535** [qwertydog/Reddit-Wallpaper-Changer#9]
I keep getting this error. `Remote server returned an error: (404) Not Found`

Full error log:
`11/6/2022 5:57:33 PM - DELL-T20 - SearchForWallpaperAsync - INFORMATION: Looking for a wallpaper.
11/6/2022 5:57:33 PM - DELL-T20 - GetRedditSearchUrl - INFORMATION: Selected sub to search: winterporn,EarthPorn,wallpaper,wallpapers,
11/6/2022 5:57:33 PM - DELL-T20 - GetRedditSearchUrl - INFORMATION: Full URL Search String: http://www.reddit.com/r/winterporn,EarthPorn,wallpaper,wallpapers,/search.json?q=1920x1080+nsfw%3Ano+self%3Ano+((url%3A.png+OR+url%3A.jpg+OR+url%3A.jpeg)+OR+(url%3Aimgur.png+OR+url%3Aimgur.jpg+OR+url%3Aimgur.jpeg)+OR+(url%3Adeviantart))&restrict_sr=on&sort=hot&t=day
11/6/2022 5:57:33 PM - DELL-T20 - GetJsonDataAsync - INFORMATION: Searching Reddit for a wallpaper.
11/6/2022 5:57:33 PM - DELL-T20 - LogFailure - ERROR: Reddit server error: The remote server returned an error: (404) Not Found.
11/6/2022 5:57:33 PM - DELL-T20 - SearchForWallpaperAsync - WARNING: The remote server returned an error: (404) Not Found.`

Hope this can be fixed! Thanks for all your work!

**Comment by qwertydog** [comment]
Hi, you need to separate the subreddits with `+` characters, you're using commas (`,`).

- Your subreddits:
```winterporn,EarthPorn,wallpaper,wallpapers,```

- Should be:
```winterporn+EarthPorn+wallpaper+wallpapers```
